[workspace]
resolver = "3"
members = [
    "pomme-client",
    "pomme-gpu-allocator",
    "pomme-block",
    "pomme-protocol",
    "pomme-singleplayer",
    "tools/blockgen",
    "tools/protogen"
]
# Exclude third_party and desktop-only Tauri launcher
exclude = [
    "third_party/SteelMC",
    "pomme-launcher/src-tauri"
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
directories = "6"
sha1_smol = "1"
open = "5"
base64 = "0.23"
zip = { version = "8.6", default-features = false, features = ["deflate"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13", features = ["json"] }
glam = "0.33"

# client
pyronyx = "=0.4.0"
regex = "1"
chrono = { version = "0.4.44", features = ["serde"] }
rand = "0.10.2"
rsa = "0.10.0-rc.18"
sha1 = "0.11"
sha2 = "0.11"
tracing = "0.1"
tracing-subscriber = "0.3"

[patch.crates-io]
azalea-buf = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-protocol = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-crypto = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-auth = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-entity = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-world = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-block = { path = "pomme-block" }
azalea-chat = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-core = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-registry = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }
azalea-inventory = { git = "https://github.com/azalea-rs/azalea", branch = "26.2" }

[patch."https://github.com/azalea-rs/azalea"]
azalea-block = { path = "pomme-block" }

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 2

# Mirrors steel's dev overrides
[profile.dev.package.steel-worldgen]
opt-level = 3
debug-assertions = false
overflow-checks = false

[profile.dev.package.steel-math]
opt-level = 3
debug-assertions = false
overflow-checks = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
